name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main
      - functions-3-and-4

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./lambda_IV_from_dynamo # Replace with the path to the folder containing your Dockerfile
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/meffscrapping_iv:latest 

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name meffscrapping_iv \
          --image-uri ${{ steps.login-ecr.outputs.registry }}/meffscrapping_iv:latest \
          --region eu-central-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
